integration:
  eventlog:
    connectTimeout: 19
    logKeyUuid: 00000000-0000-0000-0000-000000000000
    readTimeout: 21
    url: http://localhost:${wiremock.server.port:}/api-eventlog
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          schema-generation:
            script:
              append: false
      jakarta:
        persistence:
          schema-generation:
            create-source: metadata
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
  security:
    oauth2:
      client:
        provider:
          eventlog:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          eventlog:
            client-id: the-client-id
            client-secret: the-client-secret
