integration:
  eventlog:
    logKeyUuid: 00000000-0000-0000-0000-000000000000
    url: http://localhost:${wiremock.server.port:}/api-eventlog
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.4:///
  flyway:
    enabled: true
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: validate
  security:
    oauth2:
      client:
        provider:
          eventlog:
            token-uri: http://localhost:${wiremock.server.port:}/api-gateway/token
        registration:
          eventlog:
            client-id: the-client-id
            client-secret: the-client-secret
