integration:
  eventlog:
    connectTimeout: 5
    readTimeout: 30
logging:
  level:
    root: INFO
openapi:
  name: ${spring.application.name}
  title: ${spring.application.name}
  version: '@project.version@'
spring:
  application:
    name: api-document
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      pool-name: document-pool
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        auto_quote_keyword: true
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
    show-sql: false
  security:
    oauth2:
      client:
        registration:
          eventlog:
            authorization-grant-type: client_credentials
            provider: eventlog
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
springdoc:
  swagger-ui:
    operationsSorter: alpha
